# https://github.com/Asabeneh/30-Days-Of-Python/blob/master/04_Day_Strings/04_strings.md#-exercises---day-4

print(" ".join(['Thirty', 'Days', 'Of', 'Python']))
print(" ".join(['Coding', 'For' , 'All']))
company = "Coding For All"
print(company)
print(len(company))
print(company.upper())
print(company.lower())
print(company.capitalize())
print(company.title())
print(company.swapcase())
print(company[0:6])
print("Coding" in company)
print(company.replace("Coding","Python"))
print(company.split())
print("Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon".split(" ,"))
print(company[0])
print(len(company)-1)
print(company[10])
print("".join([s[0] for s in "Python For Everyone".split()]))
print("".join([s[0] for s in company.split()]))
print(company.index("C"))
print(company.index("F"))
print("Coding For All People".rfind("l"))
print('You cannot end a sentence with because because because is a conjunction'.index("because"))
print('You cannot end a sentence with because because because is a conjunction'.rindex("because"))
print('You cannot end a sentence with because because because is a conjunction'[31:54])
print(company.startswith("Coding"))
print(company.endswith("coding"))
print('   Coding For All      '.strip(' '))
print("30DaysOfPython".isidentifier())
print('thirty_days_of_python'.isidentifier())
print(" ".join(['Django', 'Flask', 'Bottle', 'Pyramid', 'Falcon']))
print("I am enjoying this challenge.\nI just wonder what is next.")
print("Name\tAge\tCountry\tCity")
print("Asabene\t250\tFinland\tHelsinki")
radius = 10
area = 3.14 * radius ** 2
print("The area of a circle with radius {:.0f} is {:.0f} meters square.".format(radius,area)) # {.0f} means 0 decimal places